# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3cf1c19acdbf12d3ba8bd1275d2396cd2907798404c2464baceb1626d8f7281c84f43eec8af9108a978785a72139a68cb4681a929c24887658d0cf955e4ad58

test:
  secret_key_base: bf08a18058d87a78dce1d69c76fec07c086d64267ab1f62814a15cf442c6822a2deb90715084319b5fd7dc3a0b5ff32e5103c501a10ba0e9f1b8f909a1740365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
